#ifndef MORANDOMIZER_VERSION_H
#define MORANDOMIZER_VERSION_H

#define MORANDOMIZER_VERSION_MAJOR 0
#define MORANDOMIZER_VERSION_MINOR 0
#define MORANDOMIZER_VERSION_PATCH 0
#define MORANDOMIZER_VERSION_BUILD 2

#define MORANDOMIZER_VERSION_STRING "0.0.0.2"

#endif // MORANDOMIZER_VERSION_H
